$ErrorActionPreference='Stop'
$dir = Join-Path $env:USERPROFILE '.openclaw\workspace\teams_app_openclaw_v2'

# icons generated by gen_icons.ps1

$zip = Join-Path (Split-Path $dir -Parent) 'OpenClawChat-TeamsApp-v2.zip'
if (Test-Path $zip) { Remove-Item $zip -Force }
Compress-Archive -Path (Join-Path $dir '*') -DestinationPath $zip
Write-Output $zip
